str = "asim is my boss"
print(str.strip())
print(str.upper())
print(str.lower())
print(str.capitalize())
print(str[11:15])
print(str.replace("boss","abbu"))
print(str.endswith("abbu"))
print(str.startswith("asim"))
print(str.split())
print(str.find("my"))
print(str.index("boss"))
new = list(str)
print(new)
new1 = "".join(new)
print(new1)